using System;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using WorkNest.Application.DTOs.Agreement;

namespace WorkNest.Infrastructure.ExternalServices.Pdf
{
    /// <summary>
    /// The "Electronic signature certificate" page appended to an agreement the customer signed in the portal:
    /// who signed, when (Pakistan time), from where, the signature itself and the SHA-256 of the agreement as presented.
    /// </summary>
    public static class ESignatureCertificatePdfGenerator
    {
        static ESignatureCertificatePdfGenerator()
        {
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public static byte[] Generate(AgreementESignatureEvidence e)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily("Arial").FontColor("#1e293b").LineHeight(1.3f));

                    page.Header().Column(col =>
                    {
                        col.Item().Text("Electronic signature certificate").FontSize(18).Bold().FontColor("#0f172a");
                        col.Item().PaddingTop(2).Text($"Lease agreement #{e.AgreementId}" +
                            (string.IsNullOrWhiteSpace(e.QuotationNumber) ? "" : $" · Quotation {e.QuotationNumber}"))
                            .FontSize(10).FontColor("#64748b");
                        col.Item().PaddingTop(10).LineHorizontal(1).LineColor("#cbd5e1");
                    });

                    page.Content().PaddingTop(16).Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text("This page records that the agreement on the preceding pages was signed electronically " +
                                        "by the person named below through the WorkNest customer portal. The signer confirmed: " +
                                        "\"I have read the agreement and agree to sign it electronically; my electronic signature " +
                                        "has the same effect as a handwritten one.\"").FontSize(9.5f).FontColor("#334155");

                        col.Item().Border(1).BorderColor("#e2e8f0").Table(table =>
                        {
                            table.ColumnsDefinition(c =>
                            {
                                c.ConstantColumn(150);
                                c.RelativeColumn();
                            });

                            void Row(string label, string? value)
                            {
                                table.Cell().Background("#f8fafc").BorderBottom(1).BorderColor("#e2e8f0").Padding(7)
                                    .Text(label).Bold().FontSize(9).FontColor("#475569");
                                table.Cell().BorderBottom(1).BorderColor("#e2e8f0").Padding(7)
                                    .Text(string.IsNullOrWhiteSpace(value) ? "—" : value).FontSize(9.5f);
                            }

                            Row("Agreement", $"#{e.AgreementId}");
                            Row("Quotation", e.QuotationNumber);
                            Row("Customer", e.CustomerName);
                            Row("Signed by", e.SignerName);
                            Row("Signer email", e.SignerEmail);
                            Row("Signed on (PKT)", e.SignedAt.ToString("dd MMMM yyyy, hh:mm:ss tt") + " (Pakistan Standard Time)");
                            Row("IP address", e.IpAddress);
                            Row("Browser / device", e.UserAgent);
                            Row("Agreement SHA-256", e.DocumentSha256);
                        });

                        col.Item().PaddingTop(6).Text("Signature").Bold().FontSize(10).FontColor("#0f172a");
                        col.Item().Width(300).Height(110).Border(1).BorderColor("#cbd5e1").Background("#ffffff").Padding(8)
                            .AlignCenter().AlignMiddle().Image(e.SignatureImage).FitArea();
                        col.Item().Text(e.SignerName).FontSize(9).FontColor("#475569");

                        col.Item().PaddingTop(10).Text("The SHA-256 value is the fingerprint of the agreement document exactly as it was " +
                                                       "presented to the signer for signing, before this certificate page was added.")
                            .FontSize(8).Italic().FontColor("#64748b");
                    });

                    page.Footer().AlignCenter().Text(t =>
                    {
                        t.Span("Generated by WorkNest · ").FontSize(8).FontColor("#94a3b8");
                        t.Span(e.SignedAt.ToString("dd MMM yyyy HH:mm")).FontSize(8).FontColor("#94a3b8");
                    });
                });
            }).GeneratePdf();
        }
    }
}
